services:
  db:
    image: mysql:8.4
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    restart: always
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      target: production
    restart: always
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: fastapi dev app/main.py --port $BACKEND_PORT --host 0.0.0.0
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$BACKEND_PORT/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web
      target: build
    command: npm run dev
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    restart: always
    env_file: .env
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
